# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.synced_folder '../', '/pixelfed'
  # set vbguest auto_update to false, we do NOT want to automatically update VirtualBox Guest Additions on the box
  config.vbguest.auto_update = false

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 2

  end

  # Bullseye
  config.vm.define :bullseye do |bullseye|
    bullseye.vm.box = 'bento/debian-11'
    bullseye.vm.provision :shell, name: 'install tools', path: './shell/bullseye/installer_root'
    bullseye.vm.provision :shell, name: 'install user tasks', privileged: false, path: './shell/bullseye/installer_user'
    bullseye.vm.network :private_network, ip: '192.168.50.50'
  end
end
