#!/bin/bash

set -x

apt-get install -y git curl gnupg jq 

wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list

curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list

mkdir -p /etc/apt/keyrings

curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

export NODE_MAJOR=20 
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

apt-get update

apt-get install -y lsb-release apt-transport-https ca-certificates 

apt-get install -y  php8.2 php8.2-cli php8.2-fpm php8.2-curl php8.2-mysql \
                    php8.2-bcmath php8.2-intl php8.2-zip php8.2-xml \
                    php8.2-mbstring php8.2-redis

apt-get install -y sqlite3 libsqlite3-dev

apt-get install -y ffmpeg mariadb-server

apt-get install -y nodejs

/vagrant/shell/bullseye/install-mariadb.sh

apt-get install -y redis