#!/bin/bash

set -x

cd /pixelfed

/vagrant/shell/bullseye/composer-install.sh

echo "composer.phar update"
php composer.phar update

echo "php artisan install --dangerously-overwrite-env"
# php artisan install --dangerously-overwrite-env

# php artisan cache:clear
# php artisan optimize:clear
# php artisan optimize

# php artisan config:cache
# php artisan route:cache
# php artisan view:cache

# php artisan migrate --force

# npm install
# npm run production

# php artisan serve --host=0.0.0.0
